### ISSUE TITLE
feature request x2

### ISSUE THREAD

**Issue by ajrossnz** [opicron/mysticbbs-rjam#1]
1) set areas to 'read' or 'caught up' ala the Ctrl+C option of the stock Mystic reader.
2) provide a way to search for an area name, eg, press a hotkey then start typing name of area or description to match results.

These are my feature requests, however I was given these exact requests from another user of the mod on my BBS today, so consider that at least 2 people wanting this on their wish list 😁.

**Comment by opicron** [comment]
These will definately be implemented. This month I had to work on a project, no time. Next month I will try to get them in.

**Comment by opicron** [comment]
Basic search functionality for areas tested now. Cant be very long now =).

**Comment by ajrossnz** [comment]
Any updates? Sorry to be a pain!

**Comment by opicron** [comment]
Hiya man, I just added in beta (on bbs.theforze.eu) the Catch up and Set scan date options. Want to check it out? If you like how it works with the default Mystic prompts I will add to this release.

**Comment by opicron** [comment]
Added..
