### ISSUE TITLE
Bug with /YOU /NEW flags?

### ISSUE THREAD

**Issue by ajrossnz** [opicron/mysticbbs-rjam#2]
When using the /YOU /NEW flags as described in the readme, I get a message saying 'No messages in TEST based found [press any key]'. 
I attach a video of the issue, just in case I am doing something wrong. Basically, I intended on using this feature to remove the need to use the builtin Mystic global new mail scan.
[https://youtu.be/91Z8ZEEeVGQ](https://youtu.be/91Z8ZEEeVGQ)

**Comment by opicron** [comment]
Very clear, I will find out the cause.

**Comment by opicron** [comment]
I think it has to do with last scan date of message base.

**Comment by ajrossnz** [comment]
Hey! I use a46.

**Comment by opicron** [comment]
I made some updates in the code, especially how some email/netmail/local/remote bases are handled. Would you be so kind to check the new code and see if the same happens?

**Comment by opicron** [comment]
By the way, this is how I use the newmailscan:
rjam /YOU /NOFROM /NEW

**Comment by opicron** [comment]
Ok, I found the issue. Adjusted some logic in processmsg function.

**Comment by ajrossnz** [comment]
Hey dude, I just managed to check it out and it looks good. If you want to check it on my BBS that would be ace. Press S from the messages menu!

Thanks!

**Comment by opicron** [comment]
Please update to new release, there was a logic flaw in previous code. Sorry
