### ISSUE TITLE
API mismatch for module mystic_bbs

### ISSUE THREAD

**Issue by nolageek** [opicron/mysticbbs-rjam#4]
I keep getting this error:

Python execution exception    C API version mismatch for module mystic_bbs: This Python has API version 1013, module mys
Press a key version 23135221.

**Comment by opicron** [comment]
The module mystic_bbs is written by g00r00, the author of Mystic BBS. Maybe this is some version mismatch with Python? Do other Python scripts run fine?

**Comment by nolageek** [comment]
The python demos work in the demos menu.  I'm running python27.

This is the full error:

sys:1: RuntimeWarning: Python C API version mismatch for module mystic_bbs: This Python has API version 1013, module mystic_bbs has version 23200757.

**Comment by opicron** [comment]
This has almost nothing to do with mystic_bbs module at all, I fear. The warning message you're receiving come as a result of using an ".so" file generated via compilation using one version of Python but used under another version of Python.

**Comment by opicron** [comment]
the fact that other scripts run, which might not include mystic bbs module, means that they are compatible with the api calls.

**Comment by nolageek** [comment]
SHould this be run with python 2 or 3?  (I have python27 and python311 installed)

**Comment by opicron** [comment]
Python 2.7 should be correct.

**Comment by nolageek** [comment]
I had not managed to fix it! I'll download when I get home and will test it!

"Human beings, who are almost unique in having the ability to learn from
the experience of others, are also remarkable for their apparent
disinclination to do so."
~ Douglas Adams

**Comment by opicron** [comment]
Closed, wontfix.
