### ISSUE TITLE
Error on /MAILLIST switch

### ISSUE THREAD

**Issue by robbiew** [opicron/mysticbbs-rjam#7]
Hello! I've created a menu item ("/R") to use rjam to start reading whatever area the user is in. 
It runs `rjam /MAILLIST` and then throws this error:

![Screenshot 2023-11-01 12:28:24](https://github.com/opicron/mysticbbs-rjam/assets/418170/c33cae18-44a3-4492-a734-c17fb07b2ea0)

**Comment by opicron** [comment]
Thanks for pointing this out. I will have a look!

**Comment by opicron** [comment]
Fixed!
